# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Set default environment variable values during build
ARG MY_ENV_VAR_DEFAULT=value_from_dockerfile
ENV MY_ENV_VAR=$MY_ENV_VAR_DEFAULT

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run a script during build to update config.json
RUN echo '{"hf_token": "'"$MY_ENV_VAR"'"}' > config.json

# Run app.py when the container launches
CMD ["python", "app.py"]
